import re

def classify_comment(comment_text: str) -> str:
    """
    Classifies HTML/XML comments based on CIDA/BMAD specifications.
    """
    m = re.match(r'^<!--([\s\S]*)-->$', comment_text.strip())
    if not m:
        return "unknown"
    content = m.group(1).strip()
    if not content:
        return "decorative"
    if not re.search(r'[a-zA-Z0-9]', content):
        return "decorative"
    if "generated by" in content.lower():
        return "generated"
    known_keywords = ["stepsCompleted", "workflowType", "inputDocuments", "nextStepFile", "outputFile"]
    if any(k in content for k in known_keywords):
        return "operational"
    # Try to parse as JSON - if valid, it's operational
    if (content.startswith('{') and content.endswith('}')) or (content.startswith('[') and content.endswith(']')):
        try:
            import json
            json.loads(content)
            return "operational"
        except ValueError:
            pass
    if re.search(r'^\w+\s*[:=]\s*', content):
        return "operational"
    return "unknown"

def normalize_path(path: str) -> str:
    """
    Normalizes path slashes to '/' for deterministic cross-platform compatibility.
    """
    return path.replace('\\', '/')

def is_binary_extension(filepath: str) -> bool:
    """
    Checks if a file has a known binary extension.
    """
    if not filepath:
        return False
    parts = filepath.split('.')
    if len(parts) < 2:
        return False
    ext = parts[-1].lower()
    binary_extensions = {'png', 'jpg', 'jpeg', 'gif', 'zip', 'pdf', 'exe', 'dll', 'class', 'jar', 'db', 'pyc'}
    return ext in binary_extensions
