from typing import Protocol, List, Any

class HashService(Protocol):
    def sha256(self, content: bytes) -> str:
        ...

    def sha1(self, content: bytes) -> str:
        ...

class TokenCounter(Protocol):
    def count(self, text: str) -> int:
        ...

class JsonCodec(Protocol):
    def decode(self, content: str) -> dict:
        ...

    def encode(self, data: Any, indent: int = 4) -> str:
        ...

    def canonical_encode(self, data: Any) -> str:
        ...

class YamlCodec(Protocol):
    def decode(self, content: str) -> dict:
        ...

    def parse_yaml_frontmatter_safe(self, content: str) -> dict:
        ...

class DictionaryBuilder(Protocol):
    def build_corpus_dictionary(self, all_files_content: list, token_counter: TokenCounter, min_margin: int = 5) -> dict:
        ...

class FileRepository(Protocol):
    def read_text(self, filepath: str) -> str:
        ...

    def read_bytes(self, filepath: str) -> bytes:
        ...

    def write_text(self, filepath: str, content: str) -> None:
        ...

    def write_bytes(self, filepath: str, content: bytes) -> None:
        ...

    def exists(self, path: str) -> bool:
        ...

    def is_file(self, path: str) -> bool:
        ...

    def is_dir(self, path: str) -> bool:
        ...

    def makedirs(self, path: str) -> None:
        ...

    def copy(self, src: str, dst: str) -> None:
        ...

    def remove(self, path: str) -> None:
        ...

    def is_binary_file(self, filepath: str) -> bool:
        ...

    def list_files(self, dir_path: str) -> List[str]:
        ...

    def relpath(self, path: str, start: str) -> str:
        ...

    def abspath(self, path: str) -> str:
        ...

    def basename(self, path: str) -> str:
        ...

    def dirname(self, path: str) -> str:
        ...

    def join(self, *parts: str) -> str:
        ...

    def list_dir(self, path: str) -> List[str]:
        ...
